#!/usr/bin/env node

import fs from "node:fs"
import path from "node:path"

const PLACEHOLDER_REGEX = /\{(\w+)\}/g
const KEY_REGEX = /(\w+):\s*(?:"((?:[^"\\]|\\.)*)"|'((?:[^'\\]|\\.)*)')/g

async function generate() {
    const configPath = path.resolve(process.cwd(), "flint.i18n.json")
    const config = fs.existsSync(configPath)
        ? JSON.parse(fs.readFileSync(configPath, "utf-8"))
        : { directory: "./src/languages", output: "./src/types/i18n.d.ts" }

    const directory = path.resolve(process.cwd(), config.directory)
    const output = path.resolve(process.cwd(), config.output)

    if (!fs.existsSync(directory)) {
        console.error(`[Flint i18n] Language directory not found: ${directory}`)
        process.exit(1)
    }

    const files = fs.readdirSync(directory).filter(f =>
        f.endsWith(".ts") || f.endsWith(".js")
    )

    if (!files.length) {
        console.error(`[Flint i18n] No language files found in ${directory}`)
        process.exit(1)
    }

    const primaryFile = path.resolve(directory, files[0])
    const content = fs.readFileSync(primaryFile, "utf-8")

    const keys: string[] = []
    let match

    KEY_REGEX.lastIndex = 0
    while ((match = KEY_REGEX.exec(content)) !== null) {
        const [, key, double, single] = match
        const value = double ?? single
        if (!value || key === "DEFAULT") continue

        const placeholders = [...value.matchAll(PLACEHOLDER_REGEX)].map(m => m[1])

        if (placeholders.length === 0) {
            keys.push(`    ${key}: never`)
        } else {
            const params = placeholders.map(m => `${m}: unknown`).join(", ")
            keys.push(`    ${key}: { ${params} }`)
        }
    }

    const outputContent = `// DO NOT EDIT THIS FILE DIRECTLY
// auto generated by @flint.js/i18n

export interface LanguageKeys {
${keys.join("\n")}
}
`

    const outputDir = path.dirname(output)
    if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true })
    }

    fs.writeFileSync(output, outputContent)
    console.log(`[Flint i18n] Generated types for ${keys.length} keys -> ${output}`)
}

generate().catch(err => {
    console.error("[Flint i18n] Failed to generate types", err)
    process.exit(1)
})
